// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.3
// source: tstream.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgVoid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgVoid) Reset() {
	*x = MsgVoid{}
	mi := &file_tstream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgVoid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgVoid) ProtoMessage() {}

func (x *MsgVoid) ProtoReflect() protoreflect.Message {
	mi := &file_tstream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgVoid.ProtoReflect.Descriptor instead.
func (*MsgVoid) Descriptor() ([]byte, []int) {
	return file_tstream_proto_rawDescGZIP(), []int{0}
}

type MsgTrigger struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *MsgTrigger) Reset() {
	*x = MsgTrigger{}
	mi := &file_tstream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgTrigger) ProtoMessage() {}

func (x *MsgTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_tstream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgTrigger.ProtoReflect.Descriptor instead.
func (*MsgTrigger) Descriptor() ([]byte, []int) {
	return file_tstream_proto_rawDescGZIP(), []int{1}
}

func (x *MsgTrigger) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MsgStreamReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TriggerId uint32   `protobuf:"varint,1,opt,name=TriggerId,proto3" json:"TriggerId,omitempty"`
	Signals   []string `protobuf:"bytes,2,rep,name=Signals,proto3" json:"Signals,omitempty"`
}

func (x *MsgStreamReq) Reset() {
	*x = MsgStreamReq{}
	mi := &file_tstream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgStreamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgStreamReq) ProtoMessage() {}

func (x *MsgStreamReq) ProtoReflect() protoreflect.Message {
	mi := &file_tstream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgStreamReq.ProtoReflect.Descriptor instead.
func (*MsgStreamReq) Descriptor() ([]byte, []int) {
	return file_tstream_proto_rawDescGZIP(), []int{2}
}

func (x *MsgStreamReq) GetTriggerId() uint32 {
	if x != nil {
		return x.TriggerId
	}
	return 0
}

func (x *MsgStreamReq) GetSignals() []string {
	if x != nil {
		return x.Signals
	}
	return nil
}

type MsgStream struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *MsgStream) Reset() {
	*x = MsgStream{}
	mi := &file_tstream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgStream) ProtoMessage() {}

func (x *MsgStream) ProtoReflect() protoreflect.Message {
	mi := &file_tstream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgStream.ProtoReflect.Descriptor instead.
func (*MsgStream) Descriptor() ([]byte, []int) {
	return file_tstream_proto_rawDescGZIP(), []int{3}
}

func (x *MsgStream) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MsgData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []uint32 `protobuf:"varint,1,rep,packed,name=Values,proto3" json:"Values,omitempty"`
}

func (x *MsgData) Reset() {
	*x = MsgData{}
	mi := &file_tstream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgData) ProtoMessage() {}

func (x *MsgData) ProtoReflect() protoreflect.Message {
	mi := &file_tstream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgData.ProtoReflect.Descriptor instead.
func (*MsgData) Descriptor() ([]byte, []int) {
	return file_tstream_proto_rawDescGZIP(), []int{4}
}

func (x *MsgData) GetValues() []uint32 {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_tstream_proto protoreflect.FileDescriptor

var file_tstream_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x74, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x74, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x22, 0x09, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x56,
	0x6f, 0x69, 0x64, 0x22, 0x1c, 0x0a, 0x0a, 0x4d, 0x73, 0x67, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65,
	0x72, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49,
	0x64, 0x22, 0x46, 0x0a, 0x0c, 0x4d, 0x73, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65,
	0x71, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x07, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x73, 0x22, 0x1b, 0x0a, 0x09, 0x4d, 0x73, 0x67,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x02, 0x49, 0x64, 0x22, 0x21, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x16, 0x0a, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0d, 0x52, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x32, 0xec, 0x01, 0x0a, 0x0f, 0x54, 0x72,
	0x69, 0x67, 0x67, 0x65, 0x72, 0x65, 0x64, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x35, 0x0a,
	0x0a, 0x4e, 0x65, 0x77, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x12, 0x10, 0x2e, 0x74, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x4d, 0x73, 0x67, 0x56, 0x6f, 0x69, 0x64, 0x1a, 0x13, 0x2e,
	0x74, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x4d, 0x73, 0x67, 0x54, 0x72, 0x69, 0x67, 0x67,
	0x65, 0x72, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x07, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x12,
	0x13, 0x2e, 0x74, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x4d, 0x73, 0x67, 0x54, 0x72, 0x69,
	0x67, 0x67, 0x65, 0x72, 0x1a, 0x10, 0x2e, 0x74, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x4d,
	0x73, 0x67, 0x56, 0x6f, 0x69, 0x64, 0x22, 0x00, 0x28, 0x01, 0x12, 0x38, 0x0a, 0x09, 0x4e, 0x65,
	0x77, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x15, 0x2e, 0x74, 0x73, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x2e, 0x4d, 0x73, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x12,
	0x2e, 0x74, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x4d, 0x73, 0x67, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x12,
	0x2e, 0x74, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x4d, 0x73, 0x67, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x1a, 0x10, 0x2e, 0x74, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x4d, 0x73, 0x67,
	0x44, 0x61, 0x74, 0x61, 0x22, 0x00, 0x30, 0x01, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x72, 0x70,
	0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tstream_proto_rawDescOnce sync.Once
	file_tstream_proto_rawDescData = file_tstream_proto_rawDesc
)

func file_tstream_proto_rawDescGZIP() []byte {
	file_tstream_proto_rawDescOnce.Do(func() {
		file_tstream_proto_rawDescData = protoimpl.X.CompressGZIP(file_tstream_proto_rawDescData)
	})
	return file_tstream_proto_rawDescData
}

var file_tstream_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_tstream_proto_goTypes = []any{
	(*MsgVoid)(nil),      // 0: tstream.MsgVoid
	(*MsgTrigger)(nil),   // 1: tstream.MsgTrigger
	(*MsgStreamReq)(nil), // 2: tstream.MsgStreamReq
	(*MsgStream)(nil),    // 3: tstream.MsgStream
	(*MsgData)(nil),      // 4: tstream.MsgData
}
var file_tstream_proto_depIdxs = []int32{
	0, // 0: tstream.TriggeredStream.NewTrigger:input_type -> tstream.MsgVoid
	1, // 1: tstream.TriggeredStream.Trigger:input_type -> tstream.MsgTrigger
	2, // 2: tstream.TriggeredStream.NewStream:input_type -> tstream.MsgStreamReq
	3, // 3: tstream.TriggeredStream.Stream:input_type -> tstream.MsgStream
	1, // 4: tstream.TriggeredStream.NewTrigger:output_type -> tstream.MsgTrigger
	0, // 5: tstream.TriggeredStream.Trigger:output_type -> tstream.MsgVoid
	3, // 6: tstream.TriggeredStream.NewStream:output_type -> tstream.MsgStream
	4, // 7: tstream.TriggeredStream.Stream:output_type -> tstream.MsgData
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tstream_proto_init() }
func file_tstream_proto_init() {
	if File_tstream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tstream_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tstream_proto_goTypes,
		DependencyIndexes: file_tstream_proto_depIdxs,
		MessageInfos:      file_tstream_proto_msgTypes,
	}.Build()
	File_tstream_proto = out.File
	file_tstream_proto_rawDesc = nil
	file_tstream_proto_goTypes = nil
	file_tstream_proto_depIdxs = nil
}
